#声明thymeleaf使用非严格的html。
spring:
  thymeleaf:
    cache: false  #cache: 是否缓存，开发模式下设置为false，避免改了模板还要重启服务器，线上设置为true，可以提高性能。
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    timeout: 10000ms
    lettuce:
      pool:
        max-active: 8
        max-wait: 10000ms
        max-idle: 200
        min-idle: 0

  #静态资源处理
  resources:
  #启用默认静态资源处理，默认启用
   add-mappings: true
   cache:
    cachecontrol:
  #缓存响应时间，单位秒
     max-age: 3600
   chain:
  #资源链中启用缓存，默认启用
    cache: true
  #启用资源链，默认禁用
    enabled: true

    compressed: true
  #启用H5应用缓存，默认禁用
    html-application-cache: true
  #静态资源位置
   static-locations: classpath:/static/

  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/skill?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2b8
    username: root
    password: 12345678
  hikari:
    poolName: DateHikariCP
    minIdle: 5
    idleTimeout: 1800000
    maximum-pool-size: 10
    auto-commit: true
    max-lifetime: 30000
    connection-test-query: SELECT 1
mybatis-plus:
  mapper-locations: classpath*:/mapper/*Mapper.xml
  type-aliases-package: com.xxxx.skill.pojo
logging:
  level:
    com.xxxx.skill.mapper: debug